# Generated by Django 5.2.4 on 2025-07-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('phrasal_verb', 'Phrasal verb'), ('irregular_verb', 'Irregular verb'), ('verb', 'Verb'), ('word', 'Word')], default='word', max_length=20)),
                ('mean_english', models.TextField(blank=True)),
                ('mean_espanish', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('word_english', models.CharField(max_length=200)),
                ('word_spanish', models.CharField(max_length=200)),
                ('ipa_english', models.CharField(blank=True, max_length=200, verbose_name='Pronunciation IPA (EN)')),
                ('ipa_spanish', models.CharField(blank=True, max_length=200, verbose_name='Pronunciation IPA (ES)')),
                ('audio_english', models.FileField(blank=True, null=True, upload_to='audio/english/')),
                ('audio_spanish', models.FileField(blank=True, null=True, upload_to='audio/spanish/')),
                ('content', models.TextField(blank=True)),
                ('viewed', models.BooleanField(default=False)),
                ('mark_as', models.CharField(choices=[('review', 'Review'), ('learned', 'Learned')], default='review', max_length=10)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Flashcard',
                'verbose_name_plural': 'Flashcards',
                'ordering': ['category', 'word_english'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('cards', models.ManyToManyField(blank=True, related_name='chapters', to='flashcard.flashcard')),
            ],
            options={
                'verbose_name': 'Capítulo',
                'verbose_name_plural': 'Capítulos',
                'ordering': ['title'],
            },
        ),
    ]
