# Generated by Django 5.2.4 on 2025-07-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('session', models.PositiveIntegerField()),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('word_english', models.CharField(max_length=200)),
                ('word_spanish', models.CharField(max_length=200)),
                ('ipa_english', models.CharField(blank=True, max_length=200, verbose_name='Pronunciation IPA (EN)')),
                ('ipa_spanish', models.CharField(blank=True, max_length=200, verbose_name='Pronunciation IPA (ES)')),
                ('audio_english', models.FileField(blank=True, null=True, upload_to='audio/english/')),
                ('audio_spanish', models.FileField(blank=True, null=True, upload_to='audio/spanish/')),
                ('content', models.TextField(blank=True)),
                ('viewed', models.BooleanField(default=False)),
                ('mark_as', models.CharField(choices=[('revisar', 'Revisar'), ('aprendida', 'Aprendida')], default='revisar', max_length=10)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Flashcard',
                'verbose_name_plural': 'Flashcards',
                'ordering': ['category', 'session', 'word_english'],
            },
        ),
    ]
