# Generated by Django 5.2.4 on 2025-07-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='mark_as',
            field=models.CharField(choices=[('review', 'Review'), ('learned', 'Learned')], default='review', max_length=10),
        ),
    ]
