# Generated by Django 5.2.4 on 2025-07-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0002_alter_flashcard_mark_as'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='category',
            field=models.CharField(choices=[('phrasal_verb', 'Phrasal verb'), ('irregular_verb', 'Irregular verb'), ('verb', 'Verb'), ('word', 'Word')], default='word', max_length=20),
        ),
    ]
