# Generated by Django 5.2.4 on 2025-07-19 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0005_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='show_test',
            field=models.BooleanField(default=False),
        ),
    ]
