# Generated by Django 5.2.4 on 2025-07-19 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0006_chapter_show_test'),
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chapters', to='testapp.test'),
        ),
    ]
