# Generated by Django 5.2.4 on 2025-07-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0007_chapter_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashcard',
            options={'ordering': ['category', 'word_english'], 'verbose_name': 'Flashcard', 'verbose_name_plural': 'Flashcards'},
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='session',
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='category',
            field=models.CharField(choices=[('phrasal_verb', 'Phrasal verb'), ('irregular_verb', 'Irregular verb'), ('verb', 'Verb'), ('word', 'Word')], default='word', max_length=20),
        ),
    ]
