# Generated by Django 5.2.4 on 2025-07-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0008_alter_flashcard_options_remove_flashcard_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='mean_english',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='mean_espanish',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
