# Generated by Django 5.2.4 on 2025-07-20 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0009_flashcard_mean_english_flashcard_mean_espanish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='mean_english',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='mean_espanish',
            field=models.TextField(blank=True),
        ),
    ]
