# Generated by Django 5.2.4 on 2025-07-19 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flashcard', '0006_chapter_show_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('num_questions', models.PositiveIntegerField(default=3)),
                ('questions', models.ManyToManyField(blank=True, related_name='tests', to='flashcard.flashcard')),
            ],
        ),
    ]
